# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/vmware/antrea-operator-for-kubernetes

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - unused
    - staticcheck
    - gosec
    - goimports
    - govet
